name: clean_architecture_tdd_solid
description: Um aplicativo utilizando TDD, Clean Architecture, Design Patterns e SOLID.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  get: ^4.6.1
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
